from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

import matplotlib.pyplot as plt
import os


def create_pie_chart(ats_score):

    os.makedirs("reports", exist_ok=True)

    labels = ["Matched", "Missing"]
    values = [ats_score, 100 - ats_score]

    plt.figure(figsize=(4, 4))

    plt.pie(
        values,
        labels=labels,
        autopct="%1.0f%%",
        startangle=90
    )

    plt.title("ATS Score")

    chart_path = "reports/ats_chart.png"

    plt.savefig(chart_path)

    plt.close()

    return chart_path


def generate_pdf_report(
    user_name,
    ats_score,
    missing_skills,
    ai_summary,
    match_score,
    interview_questions
):

    os.makedirs("reports", exist_ok=True)

    pdf_path = "reports/PrepPilot_Report.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    elements = []

    # =============================
    # Title
    # =============================

    elements.append(
        Paragraph(
            "🤖 PrepPilot AI Report",
            title
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            f"<b>Candidate :</b> {user_name}",
            normal
        )
    )

    elements.append(
        Paragraph(
            "<b>Generated By :</b> PrepPilot AI",
            normal
        )
    )

    elements.append(Spacer(1, 20))

    # =============================
    # Scores Table
    # =============================

    data = [

        ["Metric", "Score"],

        ["ATS Score", f"{ats_score}%"],

        ["Resume Match", match_score]

    ]

    table = Table(
        data,
        colWidths=[3 * inch, 2 * inch]
    )

    table.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 10)

            ]

        )

    )

    elements.append(table)

    elements.append(Spacer(1, 25))

    # =============================
    # Pie Chart
    # =============================

    chart = create_pie_chart(ats_score)

    elements.append(
        Paragraph(
            "ATS Score Visualization",
            heading
        )
    )

    elements.append(
        Image(
            chart,
            width=3.8 * inch,
            height=3.8 * inch
        )
    )

    elements.append(Spacer(1, 20))
        # =============================
    # Missing Skills
    # =============================

    elements.append(
        Paragraph(
            "Missing Skills",
            heading
        )
    )

    if len(missing_skills) == 0:

        elements.append(
            Paragraph(
                "No major skills missing 🎉",
                normal
            )
        )

    else:

        for skill in missing_skills:

            elements.append(
                Paragraph(
                    f"• {skill}",
                    normal
                )
            )

    elements.append(Spacer(1, 20))

    # =============================
    # AI Resume Summary
    # =============================

    elements.append(
        Paragraph(
            "AI Resume Summary",
            heading
        )
    )

    elements.append(
        Paragraph(
            ai_summary.replace("\n", "<br/>"),
            normal
        )
    )

    elements.append(Spacer(1, 20))

    # =============================
    # Interview Questions
    # =============================

    elements.append(
        Paragraph(
            "Interview Questions",
            heading
        )
    )

    elements.append(
        Paragraph(
            interview_questions.replace("\n", "<br/>"),
            normal
        )
    )

    elements.append(Spacer(1, 20))

    # =============================
    # Footer
    # =============================

    elements.append(
        Paragraph(
            "<b>Thank you for using PrepPilot AI ❤️</b>",
            title
        )
    )

    # =============================
    # Build PDF
    # =============================

    doc.build(elements)

    return pdf_path